DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS reviews;

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);
CREATE TABLE orders (
 id SERIAL PRIMARY KEY,
 date DATE NOT NULL,
 note TEXT,
 user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE products(
    id SERIAL PRIMARY KEY,
    image_url TEXT NOT NULL,
    title TEXT UNIQUE NOT NULL,
    price DECIMAL NOT NULL
    pieces INTEGER NOT NULL,
    quantity INTEGER NOT NULL,
    strain TEXT NOT NULL,
    potency TEXT NOT NULL,
    description TEXT NOT NULL,
);
CREATE TABLE reviews(
    id SERIAL PRIMARY KEY,
    rating INTEGER NOT NULL,
    comment TEXT,
    product_id INTEGER NOT NULL,
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);